#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Apr 24 14:28:47 2017

@author: andi
adapted by fabian (4.7.2019)
"""
# from AIMSTools.ParameterSweep import ParameterSweep
# from AIMSTools.AIMSOutputReader import AIMSOutput
# from AIMSTools.GeometryFile import GeometryFile
import os
from os.path import join, isfile, isdir
from aimstools.AIMSOutputReader import AIMSOutput

import argparse

def getCalcPaths(calc_dir):
    dirs = [join(calc_dir, d) for d in os.listdir(calc_dir)]
    dirs = sorted([d for d in dirs if isfile(join(d, 'control.in'))])
    return dirs


def list_files(startpath):
    n_finished = 0
    n_errors = 0
    n_not_started = 0
    for root, dirs, files in os.walk(startpath):
        level = root.replace(startpath, '').count(os.sep)
        indent = ' ' * 4 * (level)
        print('{}{}/'.format(indent, os.path.basename(root)))
        subindent = ' ' * 4 * (level + 1)

        # Check if folder root contains a valid AIMS calculation:
        if 'geometry.in' in files and 'control.in' in files:
            # Check if AIMS output file is present
            if 'aims.out' in files:
                o = AIMSOutput(join(root, 'aims.out'))
                # Check if AIMS exited normally (i.e. was not aborted due to time limit etc.)
                if o.calculationExitedNormally():
                    n_finished += 1
                    print('\x1b[0;32;40m' + subindent + 'Finished normally' + '\x1b[0m')
                else:
                    n_errors += 1
                    print('\x1b[0;31;40m' + subindent + 'Did not finish normally' + '\x1b[0m')
            else:
                n_not_started += 1
                print('\x1b[0;33;40m' + subindent + 'No aims.out file' + '\x1b[0m')

    # Print summary
    print('='*10 +  " Summary " + '='*20)
    print('\x1b[0;32;40m' + "  {:d} calculation(s) finished normally.".format(n_finished) + '\x1b[0m')
    print('\x1b[0;31;40m' + "  {:d} calculation(s) finished with errors.".format(n_errors) + '\x1b[0m')
    print('\x1b[0;33;40m' + "  {:d} calculation(s) did not start (no aims.out file present).".format(n_not_started) + '\x1b[0m')
    print('=' * 39 )

if __name__ == '__main__':
    list_files(os.getcwd())
