name: Publish

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install UV
        uses: astral-sh/setup-uv@v6
        # with:
        #   python-version: ${{ matrix.python-version }}
        #   enable-cache: true
        #   cache-dependency-glob: "uv.lock"
      # - name: Build project
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version-file: "pyproject.toml"
      - name: Build package
        run: uv build
      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish:
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/project/dfttoolkit/
    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
