name: Run the ruff linter and formatter

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  ruff-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          src: "./dfttools"
          args: "check --fix --config ./pyproject.toml --output-format=github"

  ruff-format:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          src: "./dfttools"
          args: "format --config ./pyproject.toml"
