name: ruff

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  ruff-lint:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          src: "./dfttools"
          args: "check --fix --config ./pyproject.toml --output-format=github"

  ruff-format:
    runs-on: ubuntu-latest
    needs: ruff-lint
    # strategy:
    #   matrix:
    #     python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          src: "./dfttools"
          args: "format --config ./pyproject.toml"
